### PR TITLE
added configurable HTTP methods and made PATCH used for updates - Fixes #59

### LINKED ISSUE #59: make controller mapping methods configurable
e.g

``` go
controller.RestfulUpdaterMethod = "POST"
```

### PR DESCRIPTION
**Pull request by matryer**

### CODE REVIEW

**Comment by matryer** [comment]
also see https://github.com/stretchr/goweb/wiki/Using-different-HTTP-Methods-when-mapping-controllers

**Comment by justinruggles** [comment]
This is a great solution. Although with this change I'll have to manually set UpdateMany to PUT since there is no ReplaceMany (which is what I really need). At least it's only one line of code though.

**Comment by justinruggles** [comment]
It seems to not be calling Before() before Update()

**Comment by matryer** [comment]
Can you prove that with a test?

What does your Before mapping code look like?

**Comment by justinruggles** [comment]
Sorry, I think it was an unrelated bug on my end that kept me from seeing my log messages in Before().

**Pull request merged**
